# Default autoinstall profile for a Proxmox VE lab node
# using ZFS root on a mirror of the first two disks.

[global]
keyboard = "en-us"
country = "it"
fqdn = "{{FQDN}}"
mailto = "root@localhost"
timezone = "Europe/Rome"
root-password = "CHANGEME"

[network]
source = "from-dhcp"

[disk-setup]
filesystem = "zfs"
zfs.raid = "raid1"
disk-list = ["sda", "sdb"]
